### ISSUE TITLE
label_3

### ISSUE THREAD

**Issue by RohDonghyeon** [zju3dv/disprcnn#1]
First of all, thank you for providing me with such a good code.

I have a question about kitti data.
As far as i know, only label_2 is provided in the Kitti Object dataset.

Can you tell me where i get the data from label_3?

**Comment by f-sky** [comment]
Following [Stereo R-CNN](https://github.com/HKUST-Aerial-Robotics/Stereo-RCNN/issues/40), we project 3D bounding boxes to the right view to get label_3.
I have uploaded label3.tar.gz to [here](https://drive.google.com/open?id=1KRy7LnMPagIOvoksuYVouAPK8yoaqnnL).
