### ISSUE TITLE
Evaluate with the trained model block a long time and don't print any result

### ISSUE THREAD

**Issue by kukougu** [zju3dv/disprcnn#13]
I use `sh scripts/eval_with_trained_model_dist.sh`  evaluate with the trained model.
but it block here for a long time（about 14hours now）, as show below and don't print any result even nothing in `/models/kitti/pob/inference/kitti_val_pob/predictions`
![image](https://user-images.githubusercontent.com/13816288/84367392-c306b780-ac06-11ea-8960-f1d58dc9ef0d.png)

 
I use 2 GPUs and there is one gpu run as 100% and GPU memory use 7541MB. While another gpu is both 0. 
![image](https://user-images.githubusercontent.com/13816288/84366930-1fb5a280-ac06-11ea-9c17-ceed2cd0b537.png)

Is the process do iterations now and I should wait? or there is any problems?
Thank you!

**Comment by f-sky** [comment]
Try to use a single GPU and set num_workers to 0.
