### ISSUE TITLE
 Pseudo Ground-truth Generation

### ISSUE THREAD

**Issue by swords123** [zju3dv/disprcnn#15]
Can you provide the code for Pseudo Ground-truth Generation? I am very interested for how it do, Thanks!

**Comment by f-sky** [comment]
Currently, the code has not been cleaned, also, the environment is sort of complicated, so we will not release the code recently. If you are interested in the generation process, you can refer to Sec 3.3 and Sec 3.5 in the paper.
If you have any questions, please let me know.

**Comment by JiamingSuen** [comment]
To provide more information, we are preparing for the journal version of Disp R-CNN and all the code and data related to the Pseudo-GT generation process (which also includes new categories like pedestrians and cyclists) will be made available when we finish the draft version of the journal paper.
In the meanwhile, feel free to ask any questions if you are trying to reproduce this process.

**Comment by nnop** [comment]
Awesome work!
Looking forward for the pseudo-gt generation code.
