### ISSUE TITLE
hi,my  friend,i dont find such file in kitti website,could plz give them to me?

### ISSUE THREAD

**Issue by resplendent-star** [zju3dv/disprcnn#16]
in kitti  2017 3D object 

   i only  find label_2,dont find label_3 in kitti  website,could you give me about them?

**Comment by f-sky** [comment]
1. label_3 is generated by projecting 3D bounding boxes to right view images but not provided by the KITTI website. I have uploaded label_3, please download from [here](https://drive.google.com/open?id=1KRy7LnMPagIOvoksuYVouAPK8yoaqnnL).
2. pretrained_model_KITTI2015.tar is not a compressed file, please use torch.load('pretrained_model_KITTI2015.tar') to load it.
3. I have uploaded a copy of predictions.pth to [here](https://drive.google.com/file/d/1mbo-Qjtb67ZVEDdPhDqJMH2CEFdbmtYw/view?usp=sharing).

**Comment by resplendent-star** [comment]
thanks for you reply




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju3dv/disprcnn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 晚上8:22
收件人:&nbsp;"zju3dv/disprcnn"<disprcnn@noreply.github.com&gt;;
抄送:&nbsp;"485434977"<485434977@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zju3dv/disprcnn] hi,my  friend,i dont find such file in kitti website,could plz give them to me? (#16)





  
label_3 is generated by projecting 3D bounding boxes to right view images but not provided by the KITTI website. I have uploaded label_3, please download from here.
 
pretrained_model_KITTI2015.tar is not a compressed file, please use torch.load('pretrained_model_KITTI2015.tar') to load it.
 
I have uploaded a copy of predictions.pth to here.
