### ISSUE TITLE
solver for 3d?

### ISSUE THREAD

**Issue by AndreaCeccarelli** [zju3dv/disprcnn#17]
Hello

Not sure I got everything right, so I need to ask.

To my understanding, the solver in scripts/eval_with_trained_model.sh is only for 2d object detection (or better: I am getting results only for 2d evaluation on cars detection). How to reproduce results for 3d detections?

**Comment by f-sky** [comment]
There are several commands in the script, you need to run all of them to reproduce 3d detection results.

**Comment by AndreaCeccarelli** [comment]
Ops, my bad -- thanks. It works nicely!
