### ISSUE TITLE
0.0 file

### ISSUE THREAD

**Issue by RohDonghyeon** [zju3dv/disprcnn#2]
Thank you for answering the last question.
I still have a lot of difficulties, so i seem to ask questions frequently.
The difficult problem right now is i want to visualize the file value in the data->pob_roi->train->disparity->0.zarr floder->0.0 file.
can you tell me how?

**Comment by JiamingSuen** [comment]
The `0.zarr` folder can be read by the [zarr](https://zarr.readthedocs.io/) package, as demonstrated in the [data loader](https://github.com/zju3dv/disprcnn/blob/master/disprcnn/data/datasets/kitti_roi_dataset.py#L85)
Once the disparity data array is read, you can visualize the disparity with `plt.imshow(disp, cmap='jet')`.

**Comment by RohDonghyeon** [comment]
Thank you for quick response.
Let's try!

**Comment by JiamingSuen** [comment]
Feel free to reopen this issue if you met any problem.

**Comment by RohDonghyeon** [comment]
I solved what i asked before.
Thanks for a lot of help.
In the same way, i want to visually check the ground truth value of data > kitti > obejct > training > pob > mask_2.
![Screenshot from 2020-04-27 18-21-30](https://user-images.githubusercontent.com/33896710/80356130-fd650100-88b3-11ea-9237-830f9ab68bc3.png)
I think it's because the dimensions are different, but i wonder if there is another way to visualize it as a 3D image?
