### ISSUE TITLE
ImportError: cannot import name '_C' from 'disprcnn' (unknown location)

### ISSUE THREAD

**Issue by JunjieChen-2020** [zju3dv/disprcnn#20]
When I run the train_net.py , the importError has been occured：(occured in "nms.py"     "from disprcnn import _C")
ImportError: cannot import name '_C' from 'disprcnn' (unknown location)

Ps: I can not find the  '_C' in  the disprcnn's _init_.py,

**Comment by f-sky** [comment]
Run sh build_and_install.sh. Could you find any error message in the output?

**Comment by JunjieChen-2020** [comment]
> Run sh build_and_install.sh. Could you find any error message in the output?

you means I need followed the step for the intall statement?
The steps is execution compeleted,and then execute the  train_msrcnn.sh.

sudo apt install libwebp-dev
# Clone repo
git clone https://github.com/zju3dv/disprcnn.git
cd disprcnn
# Install conda environment
conda env create -f environment.yaml
conda activate disprcnn
# Install Disp R-CNN
sh build_and_install.sh

**Comment by f-sky** [comment]
Sure, you should set up the environment step by step.
But the installation is not guaranteed to succeed, so you should check the output during the installation step, and check whether there is an error message.
According to your description, I guess the "sh build_and_install.sh" step fails.
Run it again and paste the output here if necessary.

**Comment by JunjieChen-2020** [comment]
/usr/local/cuda:/usr/local/cuda-9.0/bin/nvcc -I/root/miniconda3/envs/disprcnn/lib/python3.7/site-packages/torch/include -I/root/miniconda3/envs/disprcnn/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda3/envs/disprcnn/lib/python3.7/site-packages/torch/include/TH -I/root/miniconda3/envs/disprcnn/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda:/usr/local/cuda-9.0/include -I/root/miniconda3/envs/disprcnn/include/python3.7m -c src/roipool3d_kernel.cu -o build/temp.linux-x86_64-3.7/src/roipool3d_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O2 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=roipool3d_cuda -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
unable to execute '/usr/local/cuda:/usr/local/cuda-9.0/bin/nvcc': No such file or directory
error: command '/usr/local/cuda:/usr/local/cuda-9.0/bin/nvcc' failed with exit status 1

Can you navigate through these errors

**Comment by f-sky** [comment]
Run the following commands and observe the outputs.
```bash
echo $CUDA_HOME
echo $LD_LIBRARY_PATH
```
reference [here](https://github.com/open-mmlab/mmdetection/issues/2113) if necessary.

**Comment by JunjieChen-2020** [comment]
perfect！build_and_install.sh is succeeded. can I run train_msrcnn.sh?

**Comment by f-sky** [comment]
Yes, you can start to train the model. Issue closed.
