### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'models/kitti/pob/inference/kitti_val_pob/predictions.pth

### ISSUE THREAD

**Issue by zailongchen** [zju3dv/disprcnn#22]
I can not find the file:predictions.pth.
can you  send me this file?
TKS

**Comment by f-sky** [comment]
Have you run the inference script?

**Comment by zailongchen** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'models/kitti/pob/inference/kitti_val_pob/predictions.pth'
FileNotFoundError: [Errno 2] No such file or directory: '/home/cjj/testcnn/disprcnn/disprcnn/data/kitti/object/training/calib/000000.txt'
Not run yet. I can't find the file of 'predictions.pth' and 'calib' folder. I downloaded the dataset from the website of 'http://www.cvlibs.net/datasets/kitti/eval_scene_flow.php?benchmark=stereo' and found that the folder of 'calib' has three subfolders (calib_cam_to_cam, calib_imu_to_velo, calib_velo_to_cam). I don't know which one is needed for this project.
Could you tell me how can I obtain these two files?

**Comment by f-sky** [comment]
Download the dataset from the 3D detection benchmark and organize them as described in TRAIN_VAL.md.
