### ISSUE TITLE
Prediction file reading error

### ISSUE THREAD

**Issue by zailongchen** [zju3dv/disprcnn#23]
Hi nice guy, I have run your trained model and obtained multiple files with the suffix .pkl. When I process them using the "pickle" package, I get the follow error:     
data = pickle.load(f)
ModuleNotFoundError: No module named 'disprcnn'
Could you tell me how to obtain the inference results and analyse them? I am looking forward to your reply! Thank you!

My processing code is as follows:
import pickle
path = './000001.pkl'
f = open(path, 'rb')
data = pickle.load(f)
print(data)

**Comment by f-sky** [comment]
Perform the [installation](https://github.com/zju3dv/disprcnn#install).

**Comment by zailongchen** [comment]
I have performed the installation and ran the trained model. I got the output file with the suffix .pkl. But I cannot open them. How can I read them and anlyse the results?

**Comment by f-sky** [comment]
The average precision (AP) is supposed to be reported automatically once you've performed the evaluation.
For further analysis, we have provided visualization code [here](https://github.com/zju3dv/disprcnn/blob/master/visualize.ipynb).

**Comment by zailongchen** [comment]
Okay, got it! Thank you again!

**Comment by f-sky** [comment]
Issue closed. Feel free to re-open it if you have more questions.
