### ISSUE TITLE
Pre-trained model for Pedestrain and Cyclists

### ISSUE THREAD

**Issue by Nicholasli1995** [zju3dv/disprcnn#25]
Hi, thanks for sharing this great work on GitHub. I noticed that Disp-RCNN had prediction results for Pedestrain on the official KITTI leaderboard. Is there any pre-trained model for 3D pedestrain detection?

**Comment by f-sky** [comment]
We have extended the Disp R-CNN to deal with pedestrians and cyclists, including pseudo-ground-truth generation and training. Currently, the code and data have not been cleaned, we will publish them once they are prepared.

**Comment by f-sky** [comment]
We have released trained model for pedestrians and cyclists. Pull the newest code and download the models. Please let me know if there is any questions.

**Comment by Nicholasli1995** [comment]
> We have released trained model for pedestrians and cyclists. Pull the newest code and download the models. Please let me know if there is any questions.

Thank you for the update and I'll contact you if I had further question.
