### ISSUE TITLE
can't find some file

### ISSUE THREAD

**Issue by Jinyong-Huang** [zju3dv/disprcnn#3]
thank you for opening code. I have some question. 
1. where are the pob.tar.gz and vob.tar.gz. these links are 404. 
2.would you open the disprcnn_R50_FPN_2d_srcnn_ckpt model?

**Comment by Jinyong-Huang** [comment]
can't open pretrained_model_KITTI2015.tar. It's damaged.

**Comment by RohDonghyeon** [comment]
Simply create a models/PSMNet folder and put the pretrained_model_KITTI2015.tar file in that folder.
And run the following task.
There is no need to decompress.

**Comment by Jinyong-Huang** [comment]
thanks!!!! now I have other problem.  No such file or directory: 'models/kitti/pob/smrcnn.pth'
where are the smrcnn.pth.

**Comment by Jinyong-Huang** [comment]
thanks!!!! now I have other problem. No such file or directory: 'models/kitti/pob/smrcnn.pth'
where are the smrcnn.pth.

**Comment by RohDonghyeon** [comment]
Did you execute the sh scripts/train_msrcnn.sh command corresponding to Stereo Mask R-CNN before entering the sh scripts/train_idispnet.sh command?

You must proceed sequentially from number 1.

**Comment by f-sky** [comment]
1. I have checked the pseudo-GT files and fixed them, please try to download again.
2. We have released the trained models, so if you don't want to train from scratch sequentially, feel free to download them, and start training from the trained models. For example, you can download the trained smrcnn.pth and train iDispNet and PointRCNN by yourself. See [here](https://github.com/zju3dv/disprcnn/blob/master/docs/TRAIN_VAL.md#evaluate-with-our-trained-model) for details.

**Comment by Jinyong-Huang** [comment]
always download failed. would you upload to baidu cloud?

**Comment by f-sky** [comment]
I have uploaded to baidu cloud. Here is the link.
链接:https://pan.baidu.com/s/1RPWyI6JTWaUqkZuBC1pukQ  密码:s5k1

**Comment by Jinyong-Huang** [comment]
太感谢了。
