### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by nekorobov** [zju3dv/disprcnn#30]
Hi, thank you for the code and for the work!

I am getting "Permission denied" when trying to execute sh scripts/download/model/srcnn_pretrained_2d_mrcnn_format.sh. Could you share it with "Anyone with the link"? 

Moreover, why don't you share predictions.pth for kitti_car vob and pob versions? It would be really helpful. I found that you have shared them [previously](https://github.com/zju3dv/disprcnn/issues/16), but the link is unfortunately expired. Thank you in advance!

Best regards,
Nikita

**Comment by f-sky** [comment]
I have fixed the link.
Following your suggestion, I have uploaded predictions.pth for kitti_car. You can find how to download them [here](https://github.com/zju3dv/disprcnn/blob/master/docs/TRAIN_VAL.md#use-predictionspth).

**Comment by f-sky** [comment]
Issue closed. Feel free to re-open it if you have more questions.
