### ISSUE TITLE
你好，请问有多类别检测的版本吗

### ISSUE THREAD

**Issue by qumasaike** [zju3dv/disprcnn#31]

**Comment by f-sky** [comment]
没有。理论上来说是可行的，你可以修改detection head来实现多类别。但整体的训练时间会比较长，效果也会出现一定程度的降低。

**Comment by qumasaike** [comment]
好的，我尝试一下，谢谢~

**Comment by qumasaike** [comment]
你好，请问链接里给的smrcnn预训练模型是在什么数据集上训练的呢，我如果想要实现多类别，是不是需要重新训练backbone呢

**Comment by f-sky** [comment]
smrcnn是Stereo R-CNN在car上训练的，如果多类别的话，我建议不使用Stereo R-CNN, 而是使用Mask R-CNN对左右目分别detection，然后再match RoIs，详见[这里](https://f-sky.github.io/docs/DispRCNN-TPAMI.pdf).

**Comment by qumasaike** [comment]
谢谢您的建议，我换成Mask R-CNN后，box head得到的结果比较好。但是kitti数据集中并没有mask的标注，请问链接里car_vob.zip中的mask标注是怎么生成的呢

**Comment by f-sky** [comment]
和disparity一样，是从reconstructed object render出来的。

**Comment by qumasaike** [comment]
请问相应的代码这里有吗

**Comment by f-sky** [comment]
这里没有render的代码。

**Comment by qumasaike** [comment]
好的，谢谢解答~
