### ISSUE TITLE
reported the reproduced result for PL (AVOD) without LiDAR supervision.

### ISSUE THREAD

**Issue by Sukaiqi** [zju3dv/disprcnn#32]
As far as I know, LiDAR supervision is mainly used to generate ground truth depth maps. 
So, if PSMNet does not use LiDAR supervision, how to modify it?
Can you tell me more detail about it? 
I would be very grateful to you！

**Comment by f-sky** [comment]
If you mean the reproduced result for PL (AVOD) is our paper, what we mean is that we do not use LiDAR points in the KITTI Object Dataset to train the PSMNet, but inference directly with the PSMNet trained on the KITTI Stereo Dataset.

**Comment by Sukaiqi** [comment]
你的意思是，直接用的PSMNet在KITTI 立体数据集上训练好的模型进行depth map预测吗

**Comment by f-sky** [comment]
对

**Comment by Sukaiqi** [comment]
非常感谢您的回答！！！
