### ISSUE TITLE
您好，请教一下rotate_pc_along_y这个类的作用是什么呢

### ISSUE THREAD

**Issue by qumasaike** [zju3dv/disprcnn#33]
我看代码中在pointrcnn的rpn阶段把点云和标注框绕y轴做了旋转，在rcnn阶段旋转了回去，请问这样做的目的是什么呢，以及这个旋转角度的计算有什么含义呢？
`bbox_center_w = (bbox2d[:, 0] + bbox2d[:, 2]) / 2`
` self.rot_angle = torch.atan2(bbox_center_w - w, f)`

**Comment by f-sky** [comment]
归一化。你可以可视化一下归一化之后的点云。你也可以试着不用这个归一化。
