### ISSUE TITLE
could you provide the results on KITTI val split? 

### ISSUE THREAD

**Issue by jichaofeng** [zju3dv/disprcnn#39]
I'm sorry for disturbing you again. I want to do a visual comparison with Disp R-CNN on KITTI val split , could you provide the results on KITTI val split?  Thank you very much.

**Comment by f-sky** [comment]
Download the trained models and results from [here](https://github.com/zju3dv/disprcnn/blob/master/docs/TRAIN_VAL.md).

**Comment by jichaofeng** [comment]
The results is very large , so the download speed  is slow. Do you have the results which is txt file format,like the KITTI label ?

**Comment by f-sky** [comment]
Which type do you need? If you need pixel-wise depth predictions, the file cannot be small. Try to use a proxy to download the files. You can also run the inference scripts to get the results.

**Comment by jichaofeng** [comment]
Sorry, I have not  made myself clear. I need the 3D detection results on KITTI val split.

**Comment by f-sky** [comment]
[txt.zip](https://github.com/zju3dv/disprcnn/files/7920292/txt.zip)
Here are the results for the car category.

**Comment by jichaofeng** [comment]
Thank you very much for your help.
