### ISSUE TITLE
I solved what i asked before.

### ISSUE THREAD

**Issue by RohDonghyeon** [zju3dv/disprcnn#4]
I solved what i asked before.
Thanks for a lot of help.
In the same way, i want to visually check the ground truth value of data > kitti > obejct > training > pob > mask_2.
![Screenshot from 2020-04-27 18-21-30](https://user-images.githubusercontent.com/33896710/80356130-fd650100-88b3-11ea-9237-830f9ab68bc3.png)
I think it's because the dimensions are different, but i wonder if there is another way to visualize it as a 3D image?

_Originally posted by @RohDonghyeon in https://github.com/zju3dv/disprcnn/issues/2#issuecomment-619852723_

**Comment by f-sky** [comment]
Each mask pseudo-GT has three dimensions, the first dimension is the number of objects which you can find in label_2, and the last two dimensions is the image size. (10, 375,1242) means there are 10 objects.
You can perform 'plt.imshow(mask.sum(0))' to visualize the full-image mask, or 'plt.imshow(mask[i])' to visualize the mask of the i-th object.

**Comment by f-sky** [comment]
If there are no more questions, I will close this issue.
