### ISSUE TITLE
Running on CUDA 11.0+

### ISSUE THREAD

**Issue by yujie-xing** [zju3dv/disprcnn#44]
Hi!

Thank you for your impressive work,

My colleague and I had a hard time running the codes on CUDA 11.3 and finally we came up with a solution after modifying some files in the codes. Would it be possible, and if possible, how could we share the modified codes/methods to modify the codes with you?

您好，谢谢您的工作。

我们尝试在CUDA 11.1+上运行但是失败了，我们花了很多时间终于找到了解决方法（需要修改/替换部分pointnet2的文件）。我们觉得如果能发布一个CUDA 11.3适配的版本会对很多人都有帮助，不知道您怎么看？如果您觉得可以，我们应该如何share代码/修改代码的方法给您呢？

**Comment by ootts** [comment]
I have opened a new branch "cuda11". Try to create a pull request to the "cuda11" branch, feel free to let me know if you have a problem doing that.

**Comment by yujie-xing** [comment]
Hi,

Thank you for your reply.

We are ready for pushing :) Please add the git username “aya-saad” (email: ***@***.***) so that we could push.

Best regards,
Yujie
________________________________

**Comment by ootts** [comment]
I have added the username you provided. Please try to add a pull request.

**Comment by ootts** [comment]
Pull request accepted. Thanks for your contribution. Feel free to reopen the issue if you have more questions.

**Comment by yujie-xing** [comment]
Hi,

Thank you! I will ask my colleague to create a pull request from her fork.

Best regards,
Yujie

________________________________
