### ISSUE TITLE
作者你好，请问如何在新数据上制作pseudo_gt？

### ISSUE THREAD

**Issue by zyiqin** [zju3dv/disprcnn#46]
你好，我已经复现了您的工作，想在新的数据上测试，请问如何生成对应的pseudo_gt，方便提供一下代码或者思路吗？谢谢啦

**Comment by ootts** [comment]
在新数据上测试还是训练？如果只是测试的话，不需要pseudo gt的。

**Comment by zyiqin** [comment]
测试，测试是有用到disparity_2的吧。
因为我现在用做了一点修改的kitti_val做测试，发现AP全部下降到0-0.1了，在想是哪部分数据没弄好造成的。
请问作者，我是不是要在这些做了修改的数据上重新生成disparity和mask文件呀？

**Comment by ootts** [comment]
测试是不需要的，你可以在dataset的定义里改一下代码，当split是val的时候，return一个全0的假disparity当作pseudo gt就好了。至于AP下降，你对kitti val做了什么修改？

**Comment by zyiqin** [comment]
做的修改是，比如在车子附近贴了一个行人。按理说最多会导致当前车的检测出错，不至于下降到0的

**Comment by zyiqin** [comment]
哦哦~谢谢作者指点！找到我的错误了。
