### ISSUE TITLE
mask and disparity map

### ISSUE THREAD

**Issue by RohDonghyeon** [zju3dv/disprcnn#5]
2. train Stereo Mask R-CNN
>> Isn't the result value a mask?

3.train iDispNet
>> is the result value an instance disparity map?

When loading the pickle file, which is the result of 2, the following value appears.
![1](https://user-images.githubusercontent.com/33896710/80806697-55726f00-8bf6-11ea-9562-a93412f9201f.png)

When loading the pickle file, which is the result of 3, the following value appears.
![22](https://user-images.githubusercontent.com/33896710/80806720-61f6c780-8bf6-11ea-99ce-7c7cb31c925b.png)

To solve my problem, after reading the code and loading right_prediction_per_img in the generate_psmnet_input_inf.py code, the following value also appears.
![3](https://user-images.githubusercontent.com/33896710/80806728-68853f00-8bf6-11ea-91ad-f718a08ce937.png)

Isn't there a way to see the mask and disparity map for the result 2 and 3?
like this
![Screenshot from 2020-05-01 21-51-30](https://user-images.githubusercontent.com/33896710/80806744-720ea700-8bf6-11ea-8eeb-24c80407c14b.png)

![000008](https://user-images.githubusercontent.com/33896710/80806780-8ce11b80-8bf6-11ea-8796-d08064c89f56.png)

![Screenshot from 2020-05-01 21-52-57](https://user-images.githubusercontent.com/33896710/80806759-7aff7880-8bf6-11ea-9ea1-b6996b821534.png)

The last three images are the ground truth images provided.

**Comment by RohDonghyeon** [comment]
I am looking at disprcnn3d.py and inference.py to see the test result of idispnet, but it is difficult to visualize.

**Comment by RohDonghyeon** [comment]
I want to visualization like this
![Screenshot from 2020-05-06 20-17-33](https://user-images.githubusercontent.com/33896710/81171055-b3c49680-8fd6-11ea-9891-92af69353a75.png)

**Comment by f-sky** [comment]
I have written a notebook for visualization. See [visualize.ipynb](https://github.com/zju3dv/disprcnn/blob/master/visualize.ipynb) for details.
Let me know if it does not work.

**Comment by RohDonghyeon** [comment]
Thank you for the code provided.
but i got this error.
ValueError                                Traceback (most recent call last)
<ipython-input-15-5a5ee9b64612> in <module>
----> 1 visualize(4)

<ipython-input-14-b6f0cd79c179> in visualize(idx)
     45     print(left_pred)
     46     print(right_pred)
---> 47     disp_pred=DisparityMapProcessor()(left_pred,right_pred).data*mask.float()
     48     plt.imshow(disp_pred,'jet');
     49     plt.show()

<ipython-input-3-fbd3f259d829> in __call__(self, left_predictions, right_predictions)
     45             left_predictions = [left_predictions]
     46             right_predictions = [right_predictions]
---> 47         sanity_check(left_predictions, right_predictions)
     48         results = []
     49         for l, r in zip(left_predictions, right_predictions):

<ipython-input-3-fbd3f259d829> in sanity_check(left_predictions, right_predictions)
      3 def sanity_check(left_predictions, right_predictions):
      4     assert len(left_predictions) == len(right_predictions)
----> 5     assert all(isinstance(l, BoxList) for l in left_predictions)
      6     assert all(isinstance(r, BoxList) for r in right_predictions)
      7     assert all(len(l) == len(r) for l, r in zip(left_predictions, right_predictions))

<ipython-input-3-fbd3f259d829> in <genexpr>(.0)
      3 def sanity_check(left_predictions, right_predictions):
      4     assert len(left_predictions) == len(right_predictions)
----> 5     assert all(isinstance(l, BoxList) for l in left_predictions)
      6     assert all(isinstance(r, BoxList) for r in right_predictions)
      7     assert all(len(l) == len(r) for l, r in zip(left_predictions, right_predictions))

/media/cislab/Ddrive/ROH/8DispRCNN/disprcnn/disprcnn/structures/bounding_box.py in __getitem__(self, item)
    301 
    302     def __getitem__(self, item):
--> 303         bbox = BoxList(self.bbox[item], self.size, self.mode)
    304         bbox._copy_map(self)
    305         for k, v in self.extra_fields.items():

/media/cislab/Ddrive/ROH/8DispRCNN/disprcnn/disprcnn/structures/bounding_box.py in __init__(self, bbox, image_size, mode)
     23         if bbox.ndimension() != 2:
     24             raise ValueError(
---> 25                 "bbox should have 2 dimensions, got {}".format(bbox.ndimension())
     26             )
     27         if bbox.size(-1) not in [4, 6]:

ValueError: bbox should have 2 dimensions, got 1

After completing the final evaluation with the pre-trained pointrcnn of the provided pob, and outputting it using prediction.pth, this error occurred.
