### ISSUE TITLE
About segmentation mask

### ISSUE THREAD

**Issue by dropletpeace** [zju3dv/disprcnn#9]
Thanks for sharing your code with us.
I have a question about how you trained your mask-rcnn since there is no GT mask.
Looking forward to your response.
Best wishes~

**Comment by JiamingSuen** [comment]
The mask head is trained with the generated instance masks pseudo-gt rendered together with the instance disparity pseudo-gt. If you need more detailed information like where those pseudo-gt masks are located, @f-sky can provide more information.

Additionally, manually annotated dataset like [KINS](https://github.com/qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset) would also be useful if you need more accurate mask boundaries.

Cheers~

**Comment by JiamingSuen** [comment]
Feel free to reopen this issue if you have more question.
